---
version: "2.1"
services:
  #------------------------------------------------------------------------------------------
  # IMPORTANTE: si queremos que funcionen los hardlinks y las apps -arr no repliquen las
  # descargas los directorios de transmission y las aplicaciones -arr deben de estar bajo
  # el mismo directorio
  #
  # https://wiki.servarr.com/docker-guide#Consistent_and_well_planned_paths
  #------------------------------------------------------------------------------------------

  #---------------------------------------------------
  # Sonarr - TV series
  #---------------------------------------------------
  my-sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${BASE_DIR}/config/sonarr:/config:Z
      # Directorio donde mover치 (o crear치 un hardlink) las descargas
      # de transmission
      #- ${BASE_DIR}/data:/data
      # Directorio donde transmission 'deja' los ficheros descargados
      # Sonar mover치 (o usar치 un hardlink) el fichero descargado al 
      # directorio '/data'
      - ${BASE_DIR}/data/transmission/downloads:/downloads:Z
    ports:
      - 8989:8989
    depends_on:
      - my-transmission
      - my-jackett
    restart: unless-stopped

  #---------------------------------------------------
  # Radarr - movies
  #---------------------------------------------------
  my-radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ${BASE_DIR}/config/radarr:/config:Z
      - ${BASE_DIR}/data/transmission/downloads:/downloads:Z
    ports:
      - "7878:7878"
    depends_on:
      - my-transmission
      - my-jackett
    restart: unless-stopped

  #---------------------------------------------------
  # Transmission - Client for downloading
  #---------------------------------------------------
  my-transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    privileged: true
    ports:
      - 51513:51513
      - 51513:51513/udp
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${BASE_DIR}/config/transmission:/config:Z
      - ${BASE_DIR}/data/transmission/downloads:/downloads:Z
      - ${BASE_DIR}/data/transmission/watch:/watch:Z
    restart: unless-stopped

  #---------------------------------------------------
  # Proxy for torrent searchs
  #---------------------------------------------------
  my-jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=false
    volumes:
      - ${BASE_DIR}/config/jackett:/config:Z
    ports:
      - 9117:9117
    restart: unless-stopped
