:icons: font
:source-highlighter: highlightjs
:sectnums:
:toc:


= Servarr

== Contenido del repositorio

* *compose.yaml:* con la configuración para desplegar:
** *sonarr:* para descarga de series
** *prowlarr:* buscador de torrents de las películas y series
** *transmission:* cliente para hacer las descargas usado por sonarr
* *make-dirs.sh:* para crear los directorios de persistencia de las aplicaciones anteriores
* *.env:* con las variables de entorno usadas en compose.yaml y make-dirs.sh

== Uso

* Instalamos podman y podman-compose:
+
[source, bash]
----
# Fedora
dnf install podman podman-compose
----

* Editamos el fichero *.env* para definir la ubicación del directorio donde irán las descargas:
+
[source, bash]
----
BASE_DIR=/path/base/descargas
----

* Creamos los directorios para las descargas:
+
[source, bash]
----
./make-dirs.sh
----

* Levantamos los contenedores:
+
[source, bash]
----
# -d -> detached mode
podman-compose up -d

# Para bajar los contenedores
podman-compose down
----

Una vez levantados los contenedores configuramos las aplicaciones

== Configuración de sonarr
* Accedemos a *http://localhost:8989*
* Configuramos los datos de autenticación
* Vamos a *Settings->Download clients->+* y añadimos *Transmission*. Como host usamos el hostname de la máquina o la ip pública (con *localhost* no va a funcionar)
* Configuramos el directorio donde se descargarán las series en *Settings->Media management->Root folders->Path->Add root folder*. Buscamos el directorio que creamos en el paso anterior para sonarr ($BASE_DIR/data/transmission/*downloads/tv*)
* Anotamos la API key que hay en *Settings->General->API key*

== Configuración de prowlarr
* Accedemos a *http://localhost:9696*
* Añadimos un indexer (público) en *Indexers->Add indexer* (por ejemplo EZTV, es importante elegir un valor en *Base url*)
* Configuramos las aplicaciones que van a usar prowlarr (de momento solo sonarr) en *Settings->Apps->+* y añadimos *Sonarr*. En los apartados *Prowlarr server* y *Sonarr server* tenemos que usar la ip pública de la máquina o su hostname:
** Prowlarr server: http://<host>:9696
** Sonarr server: http://<host>:8989
* Añadimos el cliente de descargas en *Settings->Download clients* (Transmission)
* Añadimos una serie en sonarr desde el menú *Series* (Add new series)

== Configuración de transmission
* Accedemos a *http://localhost:9091*
* Nos aseguramos de que el puerto que está usando transmission está abierto (menú de la esquina superior derecha en la web de transmission->*Edit preferences->Network*)


== Estructura de directorios usada
----
{DIRECTORIO_BASE}
├── config
│   ├── prowlarr
│   └── transmission
└── data
    └── transmission
        ├── downloads
        │   ├── complete
        │   ├── incomplete
        │   └── tv
        └── watch

----

Descripción de los directorios:

* *config* con las configuraciones de las aplicaciones usadas
* *data* con las descargas. Todos los directorios cuelgan de transmission para que al generar los hard links no se dupliquen los ficheros
** *transmission/downloads/complete:* descargas completadas por transmission. Cuando se completa una descarga veremos una copia aquí y otra en el directorio de la aplicación asociada pero en realidad se crea un hardlink en el directorio de la aplicación. Cuando el período definido para el seeding termine se elimina la copia de esta carpeta
** *transmission/downloads/incomplete:* descargas pendientes en transmission
** *transmission/downloads/tv:* descargas de sonarr
** *transmission/watch:* los torrents que se copien aquí serán descargados automáticamente por transmission
